project_id = "egjmyjxcizwecawsxnkn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.food-recommendations]
verify_jwt = true

[functions.realtime-health-chat]
verify_jwt = false