// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egjmyjxcizwecawsxnkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnam15anhjaXp3ZWNhd3N4bmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODIxMDgsImV4cCI6MjA2OTE1ODEwOH0.OUqGZmBjDBMfdkfsjHj6qk7B_LBamOMVEF5mlLkBb1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});